// verification.test.mjs
//
// Plain Node test script (node:test + node:assert) for api/verification.ts.
// Run with: node --test api/verification.test.mjs
//
// Every "good" vector below was independently confirmed against the real
// checksum algorithms (Verhoeff for Aadhaar, mod-36 for GSTIN, MOD-97-10 for
// IBAN) before being hard-coded here — see the derivation notes in each
// section.

import test from 'node:test';
import assert from 'node:assert/strict';

import {
  validateAadhaar,
  validatePAN,
  validateGSTIN,
  validateIFSC,
  validateIBAN,
  validateUPI,
  validateIndianMobile,
  validatePIN,
  runDeterministicChecks,
} from './verification.ts';

// ---------------------------------------------------------------------------
// Aadhaar
// ---------------------------------------------------------------------------

test('validateAadhaar: accepts a number that passes the Verhoeff checksum', () => {
  // 435231857227 was generated by brute force and confirmed to pass Verhoeff.
  const r = validateAadhaar('435231857227');
  assert.equal(r.valid, true);
});

test('validateAadhaar: accepts the same number with spaces (normalizes input)', () => {
  const r = validateAadhaar('4352 3185 7227');
  assert.equal(r.valid, true);
});

test('validateAadhaar: rejects wrong length', () => {
  const r = validateAadhaar('123456789');
  assert.equal(r.valid, false);
  assert.match(r.reason, /12 digits/);
});

test('validateAadhaar: rejects numbers starting with 0 or 1', () => {
  const r0 = validateAadhaar('023456789012');
  assert.equal(r0.valid, false);
  assert.match(r0.reason, /start with 0 or 1/);

  const r1 = validateAadhaar('123456789012');
  assert.equal(r1.valid, false);
  assert.match(r1.reason, /start with 0 or 1/);
});

test('validateAadhaar: rejects a number that fails the Verhoeff checksum', () => {
  // Same digits as the good vector but with the last digit incremented,
  // which breaks the Verhoeff checksum.
  const r = validateAadhaar('435231857228');
  assert.equal(r.valid, false);
  assert.match(r.reason, /Verhoeff/);
});

test('validateAadhaar: rejects non-numeric input', () => {
  const r = validateAadhaar('43523185722A');
  assert.equal(r.valid, false);
});

// ---------------------------------------------------------------------------
// PAN
// ---------------------------------------------------------------------------

test('validatePAN: accepts a well-formed PAN with a valid entity code and explains it', () => {
  const r = validatePAN('ABCPD1234E');
  assert.equal(r.valid, true);
  assert.match(r.reason, /Individual \(Person\)/);
});

test('validatePAN: rejects a PAN with an invalid 4th character (entity code)', () => {
  const r = validatePAN('ABCXD1234E');
  assert.equal(r.valid, false);
  assert.match(r.reason, /entity-type code/);
});

test('validatePAN: rejects a structurally wrong PAN', () => {
  const r = validatePAN('ABC1234EFG');
  assert.equal(r.valid, false);
  assert.match(r.reason, /format/i);
});

test('validatePAN: entity code decoding covers all documented letters', () => {
  const map = {
    P: 'Individual (Person)',
    C: 'Company',
    H: 'Hindu Undivided Family (HUF)',
    A: 'Association of Persons (AOP)',
    B: 'Body of Individuals (BOI)',
    G: 'Government',
    J: 'Artificial Juridical Person',
    L: 'Local Authority',
    F: 'Firm / Limited Liability Partnership',
    T: 'Trust',
  };
  for (const [code, meaning] of Object.entries(map)) {
    const pan = `ABC${code}D1234E`;
    const r = validatePAN(pan);
    assert.equal(r.valid, true, `expected ${pan} to be valid`);
    assert.ok(r.reason.includes(meaning), `expected reason to mention "${meaning}" for code ${code}`);
  }
});

// ---------------------------------------------------------------------------
// GSTIN
// ---------------------------------------------------------------------------

test('validateGSTIN: accepts a GSTIN with a correct mod-36 checksum', () => {
  // 27ABCPD1234E1ZE: state 27 (Maharashtra) + valid PAN ABCPD1234E +
  // entity count 1 + literal Z + checksum 'E' (computed via the mod-36
  // algorithm and cross-checked against validateGSTIN itself above).
  const r = validateGSTIN('27ABCPD1234E1ZE');
  assert.equal(r.valid, true);
});

test('validateGSTIN: rejects a GSTIN with a broken checksum', () => {
  const r = validateGSTIN('27ABCPD1234E1Z0');
  assert.equal(r.valid, false);
  assert.match(r.reason, /checksum/i);
});

test('validateGSTIN: rejects an invalid state code', () => {
  const r = validateGSTIN('99ABCPD1234E1ZE');
  assert.equal(r.valid, false);
  assert.match(r.reason, /state code/i);
});

test('validateGSTIN: rejects a GSTIN with an invalid embedded PAN', () => {
  // 4th char of embedded PAN 'ABCXD1234E' is 'X' -> not a valid entity code.
  const r = validateGSTIN('27ABCXD1234E1ZE');
  assert.equal(r.valid, false);
  assert.match(r.reason, /PAN/);
});

test('validateGSTIN: rejects wrong length', () => {
  const r = validateGSTIN('27ABCPD1234E1Z');
  assert.equal(r.valid, false);
  assert.match(r.reason, /15 characters/);
});

// ---------------------------------------------------------------------------
// IFSC
// ---------------------------------------------------------------------------

test('validateIFSC: accepts a well-formed IFSC', () => {
  const r = validateIFSC('HDFC0001234');
  assert.equal(r.valid, true);
});

test('validateIFSC: rejects an IFSC whose 5th character is not 0', () => {
  const r = validateIFSC('HDFC1001234');
  assert.equal(r.valid, false);
  assert.match(r.reason, /5th character/);
});

test('validateIFSC: rejects wrong length / bad characters', () => {
  const r = validateIFSC('HDF001234');
  assert.equal(r.valid, false);
});

// ---------------------------------------------------------------------------
// IBAN
// ---------------------------------------------------------------------------

test('validateIBAN: accepts a known-valid IBAN (IBAN.com example, DE)', () => {
  const r = validateIBAN('DE89370400440532013000');
  assert.equal(r.valid, true);
});

test('validateIBAN: accepts the same IBAN with spaces', () => {
  const r = validateIBAN('DE89 3704 0044 0532 0130 00');
  assert.equal(r.valid, true);
});

test('validateIBAN: rejects an IBAN with a corrupted digit (bad mod-97)', () => {
  const r = validateIBAN('DE89370400440532013001');
  assert.equal(r.valid, false);
  assert.match(r.reason, /MOD-97-10|checksum/i);
});

test('validateIBAN: rejects malformed structure', () => {
  const r = validateIBAN('123456');
  assert.equal(r.valid, false);
});

// ---------------------------------------------------------------------------
// UPI
// ---------------------------------------------------------------------------

test('validateUPI: accepts a well-formed VPA', () => {
  const r = validateUPI('someone@okhdfcbank');
  assert.equal(r.valid, true);
});

test('validateUPI: rejects a string with no @ handle', () => {
  const r = validateUPI('not-a-upi');
  assert.equal(r.valid, false);
});

// ---------------------------------------------------------------------------
// Indian mobile
// ---------------------------------------------------------------------------

test('validateIndianMobile: accepts a plain 10-digit number starting 6-9', () => {
  const r = validateIndianMobile('9876543210');
  assert.equal(r.valid, true);
});

test('validateIndianMobile: accepts +91-prefixed number with spaces', () => {
  const r = validateIndianMobile('+91 98765 43210');
  assert.equal(r.valid, true);
});

test('validateIndianMobile: rejects a number starting with an invalid leading digit', () => {
  const r = validateIndianMobile('1234567890');
  assert.equal(r.valid, false);
  assert.match(r.reason, /6, 7, 8, or 9/);
});

// ---------------------------------------------------------------------------
// PIN code
// ---------------------------------------------------------------------------

test('validatePIN: accepts a valid 6-digit PIN starting 1-8', () => {
  const r = validatePIN('110001');
  assert.equal(r.valid, true);
});

test('validatePIN: rejects a PIN starting with 0', () => {
  const r = validatePIN('000001');
  assert.equal(r.valid, false);
  assert.match(r.reason, /1-8/);
});

test('validatePIN: rejects wrong length', () => {
  const r = validatePIN('1100011');
  assert.equal(r.valid, false);
});

// ---------------------------------------------------------------------------
// runDeterministicChecks
// ---------------------------------------------------------------------------

test('runDeterministicChecks: returns empty arrays when nothing matches', () => {
  const result = runDeterministicChecks([
    { label: 'Full Name', value: 'John Doe' },
    { label: 'Address', value: '123 Main Street' },
  ]);
  assert.deepEqual(result.checks, []);
  assert.deepEqual(result.signals, []);
  assert.equal(result.hardFailures, 0);
});

test('runDeterministicChecks: detects a valid PAN by label and emits a PASS', () => {
  const result = runDeterministicChecks([{ label: 'PAN Number', value: 'ABCPD1234E' }]);
  assert.equal(result.checks.length, 1);
  assert.equal(result.checks[0].status, 'PASS');
  assert.equal(result.hardFailures, 0);
});

test('runDeterministicChecks: detects an invalid Aadhaar by label and counts a hard failure', () => {
  const result = runDeterministicChecks([{ label: 'Aadhaar No.', value: '435231857228' }]);
  assert.equal(result.checks.length, 1);
  assert.equal(result.checks[0].status, 'FAIL');
  assert.equal(result.hardFailures, 1);
});

test('runDeterministicChecks: detects an identifier via value-shape sniffing even with a vague label', () => {
  // Label gives no hint, but the value is structurally a PAN.
  const result = runDeterministicChecks([{ label: 'ID Number', value: 'ABCPD1234E' }]);
  assert.equal(result.checks.length, 1);
  assert.equal(result.checks[0].status, 'PASS');
});

test('runDeterministicChecks: flags a date of birth in the future', () => {
  const result = runDeterministicChecks([{ label: 'Date of Birth', value: '01/01/2099' }]);
  const dobCheck = result.checks.find((c) => c.check === 'Date-of-birth plausibility');
  assert.ok(dobCheck, 'expected a DOB plausibility check');
  assert.equal(dobCheck.status, 'FAIL');
  assert.equal(result.hardFailures, 1);
});

test('runDeterministicChecks: flags issue date after expiry date', () => {
  const result = runDeterministicChecks([
    { label: 'Issue Date', value: '01/01/2025' },
    { label: 'Expiry Date', value: '01/01/2020' },
  ]);
  const orderCheck = result.checks.find((c) => c.check === 'Issue/expiry date ordering');
  assert.ok(orderCheck, 'expected an issue/expiry ordering check');
  assert.equal(orderCheck.status, 'FAIL');
});

test('runDeterministicChecks: passes when issue date precedes expiry date', () => {
  const result = runDeterministicChecks([
    { label: 'Issue Date', value: '01/01/2020' },
    { label: 'Expiry Date', value: '01/01/2030' },
  ]);
  const orderCheck = result.checks.find((c) => c.check === 'Issue/expiry date ordering');
  assert.equal(orderCheck, undefined, 'should not emit a FAIL check when dates are consistent (no invented PASS either, per spec — only asserts problems it can prove)');
});

test('runDeterministicChecks: flags stated age inconsistent with date of birth', () => {
  const result = runDeterministicChecks([
    { label: 'Date of Birth', value: '01/01/2000' },
    { label: 'Age', value: '10' },
  ]);
  const ageCheck = result.checks.find((c) => c.check === 'Stated age vs date of birth');
  assert.ok(ageCheck, 'expected an age-vs-DOB check');
  assert.equal(ageCheck.status, 'FAIL');
});

test('runDeterministicChecks: does not invent a date check for an ambiguous/unparseable date', () => {
  const result = runDeterministicChecks([{ label: 'Date of Birth', value: 'not-a-date' }]);
  const dobCheck = result.checks.find((c) => c.check === 'Date-of-birth plausibility');
  assert.equal(dobCheck, undefined);
});

test('runDeterministicChecks: multiple identifiers accumulate hardFailures correctly', () => {
  const result = runDeterministicChecks([
    { label: 'PAN Number', value: 'ABCPD1234E' }, // valid -> 0
    { label: 'Aadhaar No.', value: '435231857228' }, // invalid -> 1
    { label: 'IFSC Code', value: 'HDFC1001234' }, // invalid (5th char) -> 1
    { label: 'Mobile Number', value: '9876543210' }, // valid -> 0
  ]);
  assert.equal(result.checks.length, 4);
  assert.equal(result.hardFailures, 2);
});
